name: Generate-v3

on:
  schedule:
    - cron: '0 15 * * 6' # 毎週日曜日のJST 00:00 (UTC 土曜日の 15:00) に実行
  workflow_dispatch:
    inputs:
      generate:
        description: 'Run timetable generation'
        required: false
        default: 'true'
      create_pr:
        description: 'Create pull request'
        required: false
        default: 'true'

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache HTTP data
        uses: actions/cache@v4
        with:
          path: script/common/cache
          key: ${{ runner.os }}-http-cache-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-http-cache-

      - name: Set up Python
        uses: actions/setup-python@v5.4.0
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .

      - name: Generate timetable(v3)
        if: ${{ github.event_name == 'schedule' || inputs.generate == 'true' }}
        run: |
          python script/v3/main.py

      - name: Summarize changes
        if: always()
        run: |
          python script/v3/summarize_changes.py >> $GITHUB_STEP_SUMMARY

      - name: Set branch name
        if: ${{ github.event_name == 'schedule' || inputs.create_pr == 'true' }}
        id: branch_name
        run: echo "branch=feature/update-timetable-v3-$(TZ='Asia/Tokyo' date +'%Y%m%d')" >> $GITHUB_OUTPUT

      - name: Create pull request
        if: ${{ github.event_name == 'schedule' || inputs.create_pr == 'true' }}
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "Update timetable v3"
          title: "Update timetable v3"
          body: "Update timetable v3"
          branch: ${{ steps.branch_name.outputs.branch }}
          delete-branch: true
