name: Generate-v2

on:
  # 自動実行は停止
  #schedule:
  #  - cron: '0 0 1 * *' # 毎月1日の00:00に実行
  workflow_dispatch:
    inputs:
      generate:
        description: 'Run timetable generation'
        required: false
        default: 'true'
      create_pr:
        description: 'Create pull request'
        required: false
        default: 'true'

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5.4.0
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .

      - name: Generate timetable(v2)
        if: ${{ github.event_name == 'schedule' || inputs.generate == 'true' }}
        run: |
          python script/v2/main.py

      - name: Check timetable(v2)
        run: |
          python script/v2/check_timetable.py --mode directory --path ./database/kanachu/v2/database --ignore busstops.json,route.json

      - name: Create pull request
        if: ${{ github.event_name == 'schedule' || inputs.create_pr == 'true' }}
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "Update timetable v2"
          title: "Update timetable v2"
          body: "Update timetable v2"
          branch: "feature/update-timetable-v2"
          delete-branch: true
