name: Release-v2

on:
  push:
    branches:
      - main
    paths:
      - 'database/kanachu/v2/**'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5.4.0
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .

      - name: Release for v2
        run: |
          mkdir -p release/kanachu/v2
          HASH_V2=$(python -c "from script.common.hash import hash_directory; print(hash_directory('database/kanachu/v2/database'))")
          python script/common/edit_json.py update release/kanachu/v2/info.json "hash" $HASH_V2
          pushd database/kanachu/v2/database
          zip -r ../../../../release/kanachu/v2/database.zip .
          popd

      - name: Inspect ZIP contents
        run: unzip -l release/kanachu/v2/database.zip

      - name: Create pull request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "Automated changes"
          title: "Release v2"
          body: "Release v2"
          branch: "release/v2"
          add-paths: "release"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: timetable-database-v2
          path: release/kanachu/v2
