name: Release-v3

on:
  # リリースの仕方は見直すので、いったん止める
  #push:
  #  branches:
  #    - main
  #  paths:
  #    - 'database/kanachu/v3/**'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5.4.0
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .

      - name: Release for v3
        run: |
          python script/v3/release.py

      - name: Inspect release contents
        run: ls -R release/kanachu/v3
      - name: Create pull request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "Automated changes"
          title: "Release v3"
          body: "Release v3"
          branch: "release/v3"
          add-paths: "release"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: timetable-database-v3
          path: release/kanachu/v3
